### ISSUE TITLE
Github Registry support

### ISSUE THREAD

**Issue by Elecweb** [swarmpit/swarmpit#402]
Can I add github registry via custom registry? if not, it'd be great to support github registry

**Comment by nohaapav** [comment]
@Elecweb Github has finally registry ? Will check that out. However if registry implements standard v2 api then yes it should be possible.

**Comment by Elecweb** [comment]
Yes but it's still in beta version. I tried using custom registry v2 but it doesn't seems to work. 

I use `docker.pkg.github.com` as registry url, github username as username and github personal token as password.

https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-docker-for-use-with-github-package-registry

I think it need to have seperate add registry for github like an gitlab registry

**Comment by pospile** [comment]
This would be great improvement!

**Comment by Uysim** [comment]
Any update on this?

**Comment by nohaapav** [comment]
We'll add support in 2.0 ..

**Comment by nohaapav** [comment]
Did you managed to get `docker-content-digest` from github package registry ?

**Comment by nohaapav** [comment]
Update: Finally `ghcr.io` solves the issues mentioned here: https://github.com/swarmpit/swarmpit/issues/402#issuecomment-683670055

Unfortunately we're still not able to list images related to user or organization because graphql v4 API is not working
properly and registry v2 `/_catalog` api is not supported as well. Attaching discussions:

https://github.community/t/github-container-registry-ghcr-io-packages-not-appearing-in-api/130133/2
https://github.community/t/ghcr-io-docker-http-api/130121/7

**Comment by pedrofracassi** [comment]
Hey, how's this going? I love swarmpit but need to deploy some private images hosted on GH CR

**Comment by mrspartak** [comment]
Any updates on this?

**Comment by nwilging** [comment]
Azure and gitlab support but no GHCR? Oof.

**Comment by nohaapav** [comment]
@nwilging Basically support is implemented, there was problem on GH side in the very beginning. Solution is just not merged into master. I'll take a look into this soon and merge it into master.

**Comment by danstis** [comment]
Does anyone have a workaround for this issue?
Or do you currently just deploy the stacks outside of swarmpit currently?

**Comment by tomas-kulhanek** [comment]
im try it, but it not working for me :( I alway get 405 code

**Comment by nohaapav** [comment]
@lumir-mrkva Do you think we can make it to 1.10 ?

**Comment by jozefrebjak** [comment]
Hello, @nohaapav I'm trying to use private image with settings provided by @danstis in one of the stack and I'm getting error:

```
Stack deployment failed. WARNING! Using --password via the CLI is insecure. 
Use --password-stdin. Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
```

Registry was added successfully.

**Comment by skjnldsv** [comment]
> ```
> Stack deployment failed. WARNING! Using --password via the CLI is insecure. 
> Use --password-stdin. Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
> ```

It means you have given an invalid token in the password field on swarmpit.
Try with a new one or double check the permissions scope

**Comment by mrq1911** [comment]
done

**Comment by 12joan** [comment]
@mrq1911 Please could you clarify what the current status of GHCR support is? I can see that `ghcr` is now referenced in [one place in the code](https://github.com/swarmpit/swarmpit/blob/510312bf529f9eb2648c110bec67f806bda5940b/src/clj/swarmpit/authorization.clj#L57), but it still isn't an option in Swarmpit's UI when creating a registry.

I've currently got GHCR set up as a v2 registry with the following config:
- URL: `https://ghcr.io`
- Custom API: disabled
- Secured access: enabled
- Username: my GitHub username
- Password: a PAT with `read:packages` only

With this setup, I can see in the logs for Swarmpit's container a large number of failed requests to GHCR where Swarmpit is using `Authorization Basic <base64 encoded username:password>` and GHCR is replying with `401 Unauthorized` and `www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:user/image:pull"`.

However, I also found (by temporarily proxying GHCR through an Nginx server configured to log out all requests and their headers) that after each failed request, Swarmpit makes a subsequent successful request that doesn't appear in the logs. For these successful requests, Swarmpit uses `Authorization Bearer <base64 encoded password>`, and it also includes the `client_id`, `scope` and `service` query parameters in the URL (which were absent from the previous attempt). GHCR responds to this with `200 OK`.

```mermaid
sequenceDiagram
Swarmpit->>GHCR: HEAD /v2/USERNAME/REPO/manifests/main<br>Authorization: Basic BASE64_ENCODED_USERNAME:PASSWORD>
GHCR-->>Swarmpit: HTTP/1.1 401 Unauthorized<br>www-authenticate: Bearer realm="https://ghcr.io/token",<br>service="ghcr.io",<br>scope="repository:user/image:pull"
Swarmpit->>GHCR: HEAD /v2/USERNAME/REPO/manifests/main?<br>client_id=swarmpit&<br>scope=repository:user/image:pull&<br>service=ghcr.io<br>Authorization: Bearer BASE64_ENCODED_PASSWORD
GHCR-->>Swarmpit: HTTP/1.1 200 OK
```

I'm hoping that this is sufficient for Swarmpit's auto-redeploy feature to work correctly (which is the only thing I need the registry configuration for), but I haven't had a chance to test it yet. I'll add another comment below if it turns out to be broken.
